#!/usr/bin/env python3
import sys
import requests

user=""
shame = ""
urlStart = "https://github.com/"
urlEnd = "/actions/workflows/python-app.yml/badge.svg"

def runSiren():


if len(sys.argv) == 2 or len(sys.argv) == 3:
    print("USAGE: gitBuildCheck <--shame> <username/repo>")
    print("OR")
    print("USAGE: gitBuildCheck <username/repo> <--shame>")

if len(sys.argv) == 2:
    user = sys.argv[1]

if len(sys.argv) == 3:
    if sys.argv[1] == "--shame":
        shame = sys.argv[1]
        user = sys.argv[2]
    elif sys.argv[2] == "--shame":
        shame = sys.argv[2]
        user = sys.argv[1]


urlStart += user
urlStart += urlEnd


r = requests.get(urlStart)

if r.status_code == 200:
    if "passing" in r.text:
        print("0")
        exit(0)

    if "failing" in r.text:
        if shame != "":
            pass
            #Run siren
        print("1")
        exit(1)

else:
    print("Either the username or repository was malformed")
